TEST_TEMP_TRANSACTIONS = {'FRST_ONE_OFF_RECC': {0: None},
                           'additional_position_date': {0: None},
                           'additional_position_reference': {0: None},
                           'additional_purpose': {0: None},
                           'amount': {0: '<123 EUR>'},
                           'applicant_bin': {0: 'ble'},
                           'applicant_creditor_id': {0: None},
                           'applicant_iban': {0: 'bla'},
                           'applicant_name': {0: 'bli'},
                           'bank_reference': {0: None},
                           'compensation_amount': {0: None},
                           'currency': {0: 'EUR'},
                           'customer_reference': {0: None},
                           'date': {0: '2018-01-01'},
                           'debitor_identifier': {0: None},
                           'deviate_applicant': {0: None},
                           'deviate_recipient': {0: None},
                           'end_to_end_reference': {0: None},
                           'entry_date': {0: '2018-01-01'},
                           'extra_details': {0: ''},
                           'funds_code': {0: 'R'},
                           'gvc_applicant_bin': {0: None},
                           'gvc_applicant_iban': {0: None},
                           'id': {0: 'N033'},
                           'old_SEPA_CI': {0: None},
                           'old_SEPA_additional_position_reference': {0: None},
                           'original_amount': {0: None},
                           'posting_text': {0: 'ONLINE-UEBERWEISUNG'},
                           'prima_nota': {0: '9310'},
                           'purpose': {0: 'dummy'},
                           'purpose_code': {0: None},
                           'recipient_name': {0: None},
                           'return_debit_notes': {0: '997'},
                           'settlement_tag': {0: None},
                           'status': {0: 'D'},
                           'transaction_code': {0: '177'}}

TEST_TEMP_SMPL_TRANSACTIONS = {'amount': {0: 123.0},
                               'applicant_bin': {0: 'ble'},
                               'applicant_iban': {0: 'bla'},
                               'applicant_name': {0: 'bli'},
                               'currency': {0: 'EUR'},
                               'date': {0: '2018-01-01'},
                               'entry_date': {0: '2018-01-01'},
                               'posting_text': {0: 'ONLINE-UEBERWEISUNG'},
                               'purpose': {0: 'dummy'},
                               'bank_name': {0: 'test_bank'},
                               'bank_blz': {0: '123'},
                               'transaction_uuid': {0: '132c986c-7b2e-4622-8fd7-c4ff67779a1e'}}

